# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0068da306e954cee7182e9631dceb8b2bcc6b8e7658088d33fa0936f6f2dc112d0d63746a025936eeb58a2e4be2b452692c69981faf6d795afcb21f86247cce2

test:
  secret_key_base: 83dde53d49eba0f30a62d9a579103c2ab42054dca4c4fe3bebf710a7bdc4a82aa9a6dc17ca0c3ddea88104347793ead6543ac124316ee8d9245fa682829fc369

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
